# *Online portal Work:*

## 2.Numpy Vs Python List: ##

In [1]:
l = range(1000000)

In [2]:
import numpy as np

In [3]:
a = np.arange(1000000)

In [4]:
%time for i in range (1,10):r = [x*2 for x in l]

Wall time: 1.52 s


In [5]:
%time for i in range (1,10):r = a * 2

Wall time: 46 ms


## 3.Multidimensional Array: ##

**Here we'll convert List into array But we can directly create Array by passing a value in it,**

In [6]:
a = [3,4]

In [7]:
np.zeros(a)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones(a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.empty(a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.arange(1,100,11)

array([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

In [11]:
# For Shape

In [12]:
n = np.arange(1,100,11)
np.shape(n)

(9,)

In [13]:
f = np.zeros((10,10))
np.shape(f)

(10, 10)

In [14]:
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
q = f.reshape(2,2,5,5)
q

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [16]:
q.dtype

dtype('float64')

In [17]:
q.ndim

4

## 4.Arithmetic with ndarray: ##

In [18]:
a = np.random.randn((10))

In [19]:
b = np.random.randn((10))

In [20]:
a

array([-1.4086111 ,  1.40595788,  0.04575127,  0.11439747,  1.03681196,
       -1.18407288,  0.87710597, -0.11499218, -1.19176105, -0.09485632])

In [21]:
b

array([ 1.35420554,  0.15825472, -0.29097036,  0.4035528 , -0.05424397,
       -0.67651967, -0.51275463, -0.16011043, -0.0300428 ,  0.88608121])

In [22]:
# Adding 2 arrays

In [23]:
a + b

array([-0.05440556,  1.5642126 , -0.24521909,  0.51795027,  0.98256799,
       -1.86059255,  0.36435135, -0.27510262, -1.22180385,  0.79122489])

In [24]:
a - b

array([-2.76281663,  1.24770316,  0.33672164, -0.28915533,  1.09105592,
       -0.50755321,  1.3898606 ,  0.04511825, -1.16171824, -0.98093754])

In [25]:
2 * a

array([-2.81722219,  2.81191577,  0.09150255,  0.22879494,  2.07362391,
       -2.36814576,  1.75421195, -0.22998437, -2.38352209, -0.18971265])

In [26]:
1 / a

array([ -0.70991916,   0.71125886,  21.85731523,   8.7414522 ,
         0.96449505,  -0.84454261,   1.14011309,  -8.69624319,
        -0.83909438, -10.54225979])

In [27]:
a

array([-1.4086111 ,  1.40595788,  0.04575127,  0.11439747,  1.03681196,
       -1.18407288,  0.87710597, -0.11499218, -1.19176105, -0.09485632])

In [28]:
a > 0

array([False,  True,  True,  True,  True, False,  True, False, False,
       False])

In [29]:
a[a > 0]

array([1.40595788, 0.04575127, 0.11439747, 1.03681196, 0.87710597])

## 5.Indexing & Slicing: ##

In [30]:
a = np.array([2,3,5,6,7])

**Normal Indexing**

In [31]:
a[3]

6

**Boolean Indexing**

In [32]:
a > 5

array([False, False, False,  True,  True])

***Now if I want a Value that What's in "True" then,***

In [33]:
a[a > 5]

array([6, 7])

**Fancy Indexing**

In [34]:
a[[0,1]]

array([2, 3])

## Slicing ##

In [35]:
x = np.random.randn(10,10)

In [36]:
x

array([[ 0.76660581,  1.47211632,  0.62118016,  0.22108767,  1.14749898,
         0.83828998, -0.29158672,  0.0834259 ,  0.78305304,  0.19939954],
       [ 0.09989833,  1.63442902, -1.68682036,  0.5796013 ,  0.01545931,
         0.19278915, -0.0982831 ,  0.66442277,  0.34236714,  1.96574245],
       [-0.08717517,  1.09190157, -0.09621257,  0.45533754,  0.37338907,
         0.37597361,  0.11066072, -0.80305761,  0.76428076,  1.01086556],
       [-1.23119869, -0.40723258, -0.27453801, -0.16715006,  1.47430587,
        -0.7342595 , -0.12162326,  0.15227938,  0.41188093, -0.92250178],
       [-0.64207624, -2.06818748,  2.01272458, -0.5252744 , -2.12170342,
        -0.40083152,  0.21116953,  0.04214837,  2.19641962,  0.47471092],
       [-0.50223948, -0.92021125, -1.2956695 ,  0.06836905,  1.75424529,
        -0.83215875,  0.63565013,  1.22527535, -1.14056032,  1.29402141],
       [-0.92921366, -0.65799128,  2.73624998,  0.65803263, -0.58223068,
         0.02489809, -0.08920969,  0.04436425

***If I want 1st row then,***

In [37]:
x[0]

array([ 0.76660581,  1.47211632,  0.62118016,  0.22108767,  1.14749898,
        0.83828998, -0.29158672,  0.0834259 ,  0.78305304,  0.19939954])

***If I want 5th coloumn in 1st row then,***

In [38]:
x[0][4]

1.1474989780021354

***If I want Odd rows then,***

In [39]:
x[1:10:2]

array([[ 0.09989833,  1.63442902, -1.68682036,  0.5796013 ,  0.01545931,
         0.19278915, -0.0982831 ,  0.66442277,  0.34236714,  1.96574245],
       [-1.23119869, -0.40723258, -0.27453801, -0.16715006,  1.47430587,
        -0.7342595 , -0.12162326,  0.15227938,  0.41188093, -0.92250178],
       [-0.50223948, -0.92021125, -1.2956695 ,  0.06836905,  1.75424529,
        -0.83215875,  0.63565013,  1.22527535, -1.14056032,  1.29402141],
       [ 0.94708806, -2.07229225,  1.08434981, -0.47343751, -1.87112946,
        -1.06441466,  1.07913174, -1.41461656,  0.77721618, -0.31289631],
       [-0.81726353,  0.91774169,  0.68255696, -0.04758106, -1.74982062,
         1.06354926, -1.10377086, -0.1900294 ,  0.38732191,  1.06456416]])

***Now If If I want coloumn from 0 to 4 With all rows in it then,***

In [40]:
x[::,0:4]

array([[ 0.76660581,  1.47211632,  0.62118016,  0.22108767],
       [ 0.09989833,  1.63442902, -1.68682036,  0.5796013 ],
       [-0.08717517,  1.09190157, -0.09621257,  0.45533754],
       [-1.23119869, -0.40723258, -0.27453801, -0.16715006],
       [-0.64207624, -2.06818748,  2.01272458, -0.5252744 ],
       [-0.50223948, -0.92021125, -1.2956695 ,  0.06836905],
       [-0.92921366, -0.65799128,  2.73624998,  0.65803263],
       [ 0.94708806, -2.07229225,  1.08434981, -0.47343751],
       [ 1.87471662,  0.14247849,  0.32336847, -2.21513675],
       [-0.81726353,  0.91774169,  0.68255696, -0.04758106]])

***Example***

In [41]:
s = np.ones((6,6))

In [42]:
s

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [43]:
s[1:-1,1:-1] = 0

In [44]:
s

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

## 6.Element wise Array:

In [45]:
a = np.array([10,3,6,7,8,12])

In [46]:
np.sqrt(a)

array([3.16227766, 1.73205081, 2.44948974, 2.64575131, 2.82842712,
       3.46410162])

In [47]:
np.power(a,2)

array([100,   9,  36,  49,  64, 144], dtype=int32)

In [48]:
y = np.array([1,2,5,9,13,14])

In [49]:
np.maximum(a,y)

array([10,  3,  6,  9, 13, 14])

## 7.np.where():

In [50]:
salary = np.array([-1,2,40000,50000,100000])

In [51]:
np.where(salary<=5,20000,salary)

array([ 20000,  20000,  40000,  50000, 100000])

In [52]:
np.where(salary<=5,"Invalid input",salary)

array(['Invalid input', 'Invalid input', '40000', '50000', '100000'],
      dtype='<U13')

In [53]:
np.where(salary<=5,"Invalid Input","Valid Salary")

array(['Invalid Input', 'Invalid Input', 'Valid Salary', 'Valid Salary',
       'Valid Salary'], dtype='<U13')

## Methamatical & Statistical Methods:

In [54]:
s = np.array([10,12,8,19,30])

In [55]:
s.mean()

15.8

In [56]:
s.cumsum()

array([10, 22, 30, 49, 79], dtype=int32)

In [57]:
s.cumprod()

array([    10,    120,    960,  18240, 547200], dtype=int32)

In [58]:
a = s > 5

In [59]:
a

array([ True,  True,  True,  True,  True])

In [60]:
a.sum()

5

In [61]:
a.any()

True

In [62]:
a.all()

True

In [63]:
a = s > 10
a

array([False,  True, False,  True,  True])

In [64]:
a.sum()

3

In [65]:
a.any()

True

In [66]:
a.all()

False

In [67]:
s

array([10, 12,  8, 19, 30])

In [68]:
s.sort()

In [69]:
s

array([ 8, 10, 12, 19, 30])

In [70]:
np.unique(s)

array([ 8, 10, 12, 19, 30])

## 9.File Input Output:

In [71]:
a = [1,2,3,4,5]

In [72]:
b = [6,7,8,9]

In [73]:
np.save("testa",a)

In [74]:
t = np.load("testa.npy")

In [ ]:
t

array([1, 2, 3, 4, 5])

In [ ]:
np.savez("testab",a=a,b=b)

In [ ]:
z = np.load("testab.npz")

In [ ]:
z

In [ ]:
z["a"]

## 10.Linear Algebra Function: 

![Screenshot (10)](https://user-images.githubusercontent.com/50514728/66200077-1296eb80-e655-11e9-99d8-5fed3edae230.png)

In [ ]:
x = np.random.randn(2,4)

In [ ]:
y = np.random.rand(4,2)

In [ ]:
x.dot(y)

In [ ]:
x.transpose()

In [ ]:
y.trace()

In [ ]:
a = np.array([[1,2,3] , [3,4,5]])

In [ ]:
b = np.array([4,5,6])

In [ ]:
a.dot(b)

In [ ]:
a.transpose()

In [ ]:
a.trace

## 11.Pseudo random Number:

In [ ]:
np.random.seed(3)

In [ ]:
np.random.normal(size=(2,3))

In [ ]:
np.random.uniform(size=(2,2))

## Reshaping: 

In [ ]:
x = np.random.randn(3,4)

In [ ]:
x

In [ ]:
x.reshape((2,3,2))

In [ ]:
x.reshape((2,3,2),order="F")

In [ ]:
x.reshape((2,3,-1))

In [ ]:
x

In [ ]:
x.ravel()

In [ ]:
x.flatten()

## Concatenate:

***Takes a sequence (tuple,list,etc,) of arrays and joins them together in order along the input axis***

In [ ]:
a = [[1,2,3],[4,5,6]]

In [ ]:
a1 = np.array(a)

In [ ]:
b = [[7,8,9],[10,11,12]]

In [ ]:
a2 = np.array(b)

In [ ]:
np.concatenate((a1,a2),axis=0)

In [ ]:
np.concatenate((a1,a2),axis=1)

***The same thing that we've done by deciding axis, We can do by just Giving [vstack(where, axis=0), hstack(where, axis=1)]***

In [ ]:
np.vstack((a1,a2))

In [ ]:
np.hstack((a1,a2))

## Split:

***-Split slices apart an array into multiple arrays along an x-axis***

In [ ]:
a = np.arange(1,15)

In [ ]:
a

In [ ]:
np.split(a,[3,8,12])

In [ ]:
x = [[1,2,3,4,5],[11,12,13,14,15]]

In [ ]:
v = np.array(x)

In [ ]:
v

In [ ]:
np.split(v,[4,6],axis=1)

In [ ]:
np.split(v,[1],axis=0)

## Tile & Repeat:

In [ ]:
a = np.array([1,2,3,4,5])

In [ ]:
a

In [ ]:
np.repeat(a,2)

In [ ]:
np.tile(a,3)